### ISSUE TITLE
Go-client 0.8.0 has a bug with pagination

### ISSUE THREAD

**Issue by workingoctopus** [nscuro/dtapac#156]
Hello. As far as I see you use 0.8.0 go-client. It has a problem with pagination. If you have over 50 projects then dtapac won't process other X projects. It was fixed in 0.9.0.

**Comment by nscuro** [comment]
Thanks for the heads up @workingoctopus! This should be resolved in v0.9.0 of dtapac: https://github.com/nscuro/dtapac/releases/tag/v0.9.0
